name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.17.0, 20.18.0, latest]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      -
        name: Install dependencies
        run: npm ci
